# Generated by Django 4.1.5 on 2023-01-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pswd', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
